
import {Text, View, StyleSheet, AppState, TouchableOpacity} from 'react-native';
import React, {Component} from 'react';
import NotiController from './NotiController';
import PushNotification from 'react-native-push-notification';

export default class AlarmScene extends Component<{}>{
  constructor(props){
    super(props);
    //this.handleAppStateChange = this.handleAppStateChange.bind(this);
    this.state = {
      seconds : 5
    };
  }

   componentDidMount()
   {
     //AppState.addEventListener('change', this.handleAppStateChange);
   }

  componentWillUnmount()
  {
    //AppState.addEventListener('change', this.handleAppStateChange);
  }

  onClickCallBack=() =>
  {
    {
      //TODO: schedule background notification
        PushNotification.localNotificationSchedule({
            id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            ticker: "My Notification Ticker", // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
            subText: "This is a subText", // (optional) default: none
            color: "red", // (optional) default: system default
            vibrate: true, // (optional) default: true
            vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
            group: "group", // (optional) add group to message
            ongoing: false, // (optional) set whether this is an "ongoing" notification

            title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
            message: "My Notification Message", // (required)
            playSound: false, // (optional) default: true
            soundName: 'ringtone.mp3', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
            number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
        });
    }
  }

  render(){

    return(
      <View
        style = {styles.container}>
        <Text> ALARM </Text>
        <TouchableOpacity
          style = {styles.button}
          onPress={this.onClickCallBack}>
        </TouchableOpacity>
        <NotiController />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  picker:{
    width : 100
  },
  container:{
    flex : 1,
    justifyContent : 'center',
    alignItems : 'center',
    backgroundColor : 'pink'
  },
  button:{
    backgroundColor: 'green',
    width: 100,
    height: 100
  }
});